### PR TITLE
Use syscall.Syscall6

### PR DESCRIPTION
**Pull request by corny**

### CODE REVIEW

**Comment by mdlayher** [comment]
Does this work on linux/386? I originally copied this hack from somewhere else.

**Comment by corny** [comment]
I think so. The function is defined for almost every platform:
https://github.com/golang/go/blob/964639cc338db650ccadeafb7424bc8ebb2c0f6c/src/syscall/asm_linux_386.s#L43

**Comment by mdlayher** [comment]
LGTM on green.

**Comment by corny** [comment]
Tests succeeded.

**Pull request merged**
