### PR TITLE
Workaround deprecated functionality on OpenBSD.

### PR DESCRIPTION
**Pull request by arktos**
Syscall BIOCSSEESENT as used in setBPFDirection is deprecated on OpenBSD. Some quick checking in CVS makes me wonder if it was ever supported. BIOCSDIRFILT however does work as intended.

### CODE REVIEW

**Comment by mdlayher** [comment]
I think a more maintainable approach in this case would be to have a single function that is compiled differently for OpenBSD rather than copying the entire file. Will that work?

**Comment by arktos** [comment]
You are quite right. I'm quiet new to Go and not yet used to the various “idioms”. Hopefully I got it right this time. Do I have to create a new pull request or is this request automatically pulling in the latest commit? I'm new to GitHub as well…
On another note, your work on this package has saved me a lot of effort, thank you!

**Comment by corny** [comment]
There is no need to change the file attributes:
```
raw_bsd.go 100644 → 100755 
```
Please leave them non-executable.

**Comment by arktos** [comment]
Done. Edited the files over SMB and forgot to reset the file permissions.

**Comment by mdlayher** [comment]
> On another note, your work on this package has saved me a lot of effort, thank you!

Glad to hear it by the way!

**Comment by mdlayher** [comment]
Not sure if you're totally done, but looks like this still isn't quite right.

**Pull request closed without merging**
