### PR TITLE
Add ability to access DGRAM packet sockets on Linux.

### PR DESCRIPTION
**Pull request by hugelgupf**
Not sure this is exactly what you would want, so I thought I'd just send it for review.

### CODE REVIEW

**Comment by hugelgupf** [comment]
ping?

**Comment by mdlayher** [comment]
Interesting change.  Do you have a concrete use case for this?

It can probably go in, but we may want to look at an additional options API for platform-specific options like this.

**Comment by hugelgupf** [comment]
I'm just tired of filling in ethernet headers myself in DHCP clients. (at least the v4 *seems* to currently have a need for raw sockets.)

**Comment by hugelgupf** [comment]
(Actually, I likely won't need to do all that after all, so nevermind :))

**Comment by mdlayher** [comment]
I forgot that DHCP clients may be a bit more awkward than servers since they don't have an IP yet. Let me know if you find a workable solution either way.

**Comment by hugelgupf** [comment]
Actually, I would like to get this in. I'm trying to eventually not use this, but right now this is the only way I can make work. I may have to screw with SO_BINDTODEVICE to get regular sockets to work. At least for DHCPv4 raw sockets seem to be necessary right now. (DHCPv6 at least has the EUI64 address to bind to...)

**Comment by mdlayher** [comment]
Superseded by #23.

**Pull request closed without merging**
